name: docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push for 2.0
        uses: docker/build-push-action@v2
        with:
          context: '2.0'
          push: true
          tags: |
            iquiw/redmica:latest
            iquiw/redmica:2.0.0
            iquiw/redmica:2.0

      - name: Build and push for 2.0-alpine
        uses: docker/build-push-action@v2
        with:
          context: '2.0/alpine'
          push: true
          tags: |
            iquiw/redmica:2.0.0-alpine
            iquiw/redmica:2.0-alpine

      - name: Build and push for 2.0-passenger
        uses: docker/build-push-action@v2
        with:
          context: '2.0/passenger'
          push: true
          tags: |
            iquiw/redmica:2.0.0-passenger
            iquiw/redmica:2.0-passenger

      - name: Build and push for 1.3
        uses: docker/build-push-action@v2
        with:
          context: '1.3'
          push: true
          tags: |
            iquiw/redmica:1.3.0
            iquiw/redmica:1.3

      - name: Build and push for 1.3-alpine
        uses: docker/build-push-action@v2
        with:
          context: '1.3/alpine'
          push: true
          tags: |
            iquiw/redmica:1.3.0-alpine
            iquiw/redmica:1.3-alpine

      - name: Build and push for 1.3-passenger
        uses: docker/build-push-action@v2
        with:
          context: '1.3/passenger'
          push: true
          tags: |
            iquiw/redmica:1.3.0-passenger
            iquiw/redmica:1.3-passenger

      - name: Build and push for 1.2
        uses: docker/build-push-action@v2
        with:
          context: '1.2'
          push: true
          tags: |
            iquiw/redmica:1.2.2
            iquiw/redmica:1.2

      - name: Build and push for 1.2-alpine
        uses: docker/build-push-action@v2
        with:
          context: '1.2/alpine'
          push: true
          tags: |
            iquiw/redmica:1.2.2-alpine
            iquiw/redmica:1.2-alpine

      - name: Build and push for 1.2-passenger
        uses: docker/build-push-action@v2
        with:
          context: '1.2/passenger'
          push: true
          tags: |
            iquiw/redmica:1.2.2-passenger
            iquiw/redmica:1.2-passenger
