name: docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    strategy:
      matrix:
        version:
          - full: '2.1.0'
            short: '2.1'
          - full: '2.0.0'
            short: '2.0'
          - full: '1.3.0'
            short: '1.3'
          - full: '1.2.2'
            short: '1.2'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push for ${{ matrix.version }}
        uses: docker/build-push-action@v2
        with:
          context: '${{ matrix.version.short }}'
          push: true
          tags: |
            iquiw/redmica:latest
            iquiw/redmica:${{ matrix.version.full }}
            iquiw/redmica:${{ matrix.version.short }}

      - name: Build and push for ${{ matrix.version }}-alpine
        uses: docker/build-push-action@v2
        with:
          context: '${{ matrix.version.short }}/alpine'
          push: true
          tags: |
            iquiw/redmica:${{ matrix.version.full }}-alpine
            iquiw/redmica:${{ matrix.version.short }}-alpine
